// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1kvT-SA1QE6-i1M5mqG-3GSgnK7b14U',
    appId: '1:110604376278:web:e3b4fb7effc1a39bedd177',
    messagingSenderId: '110604376278',
    projectId: 'myapp-31fa2',
    authDomain: 'myapp-31fa2.firebaseapp.com',
    storageBucket: 'myapp-31fa2.appspot.com',
    measurementId: 'G-N9QZWRBV31',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRmXxPfV_Mjld9sskQ-hwr5BaBT2Qn9Ts',
    appId: '1:110604376278:ios:724ddb3e206b8b41edd177',
    messagingSenderId: '110604376278',
    projectId: 'myapp-31fa2',
    storageBucket: 'myapp-31fa2.appspot.com',
    iosClientId: '110604376278-l73gb375jgpa5c6mu4gh4g5vtpu4uanm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseapp',
  );
}
